### PR TITLE
Add support for Django 4.0.

### PR DESCRIPTION
**Pull request by FlipperPA**

### CODE REVIEW

**Comment by rgs258** [comment]
@ongchi thanks for taking over this project - I'm  glad it got a new home!

Might I please trouble you for a quick merge/release of @FlipperPA changes?

**Comment by rgs258** [comment]
@ongchi ...if you are looking for some collaborators on this, @FlipperPA and I could probably help out. We're about the least experienced react devs you'll meet, but we're reasonably well motivated package maintainers.

**Comment by ongchi** [comment]
Please feel free to share your thoughts and ideas, and all contributions are welcome.

**Comment by rgs258** [comment]
ty for the release!

**Pull request merged**
