### PR TITLE
Updates to support Wagtail 5 and cleanup with Black formatter.

### PR DESCRIPTION
**Pull request by FlipperPA**
This PR includes Wagtail 5 support by changing an import path, and does some cleanup on formatting, supported Python and Wagtail versions, and trove classifiers.

### CODE REVIEW

**Comment by rgs258** [comment]
Thank you @FlipperPA . Having this will be great for our upcoming Wagtail 5 upgrade.

**Comment by FlipperPA** [comment]
Thanks @ongchi - if you could let us know when a release is cut to PyPI, that would be amazing!

**Comment by ongchi** [comment]
I am not currently using Wagtail 5, but I will take some time in the next few days to look into it. Anyway, thank you for your contribution!

**Comment by FlipperPA** [comment]
If you're using Wagtail 4, you'll notice a deprecation notice when running `runserver` :)

**Comment by ongchi** [comment]
Hi guys @FlipperPA @rgs258 , I just upload version 0.0.4 to PyPI.

Check it out here!
https://pypi.org/project/wagtail-katex/

**Comment by rgs258** [comment]
> Hi guys @FlipperPA @rgs258 , I just upload version 0.0.4 to PyPI.
> 
> Check it out here!
> https://pypi.org/project/wagtail-katex/

Thank you!!

**Comment by FlipperPA** [comment]
Thanks so much, @ongchi - your service to the community is appreciated!

**Comment by rgs258** [comment]
@ongchi you got a mention, nice! https://wagtail.org/this-week-in-wagtail/issue-134/

**Pull request merged**
